Documentation for redirectPage function
companieshouse/your-companies-web pull request #110
Opened 2024-05-20 15:06 UTC by bwallace-ch

Changes:
- Adding documentation for redirectPage function in referrerUtils.ts

2024-05-20 15:09 UTC, mmodzelewski-ch commented on src/lib/utils/referrerUtils.ts
> + *
It would be good to add here some general information what this functions is for.

2024-05-20 15:11 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-20 15:12 UTC, mmodzelewski-ch commented on src/lib/utils/referrerUtils.ts
> + * @param referrer - redirect url - the specific url prior to the url the user is currently on
I would rather say something that informs that this is the url from which the user arrive at the current url, or something like that.

2024-05-20 15:13 UTC, mmodzelewski-ch commented on src/lib/utils/referrerUtils.ts
> + * @param hrefA - expected previous page url - compared with redirect parameter to confirm if user has travelled from the page prior to the current page in the journey
Do you mean "referrer parameter", not "redirect parameter"?

2024-05-20 15:13 UTC, mmodzelewski-ch commented on src/lib/utils/referrerUtils.ts
> + * @param hrefB - expected current page url - compared with redirect parameter to account for whether user has changed language on current page, changing the url
as above

2024-05-20 15:14 UTC, mmodzelewski-ch commented on src/lib/utils/referrerUtils.ts
> + * @param hrefC - expected next page - compared with redirect parameter to account for whether a user has clicked 'back' to go to the previous page
as above

2024-05-20 15:16 UTC, mmodzelewski-ch requested changes
See the individual comments

2024-05-20 15:24 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-21 10:40 UTC, mmodzelewski-ch commented on src/lib/utils/referrerUtils.ts
> + * @returns
State what the functions returns. Something like "true if yada yada yada, false otherwise".

2024-05-21 13:37 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-21 13:54 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-21 14:19 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-21 14:20 UTC, mmodzelewski-ch approved these changes

2024-05-21 14:20 UTC, merged