IDVA6-709 - Redirect bookmarked pages
companieshouse/your-companies-web pull request #79
Opened 2024-04-24 12:59 UTC by bwallace-ch

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-709

Changes:
- Redirection functionality on page controllers
- ReferrerUtils function for page redirection
- Unit tests for controllers and redirect function

2024-04-24 13:04 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-04-24 13:33 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-04-25 11:06 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-05-01 08:18 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-01 09:44 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-01 09:58 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-01 10:51 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-01 11:13 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-01 11:20 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-01 11:31 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-01 16:13 UTC, bmchugh-ch requested changes

2024-05-01 16:13 UTC, bmchugh-ch commented on src/routers/controllers/addPresenterController.ts
> +    const referrer: string | undefined = req.get("Referrer");
Would it be worth moving this checking session data and referrers logic outside of the controllers themselves, in separate functions or did you try that at all? Meaning the navigation checking code can be the same but independent of the controllers.

2024-05-01 16:14 UTC, mmodzelewski-ch submitted a review, later dismissed

2024-05-02 09:47 UTC, ch-code-analysis commented
CI: No security warnings found

2024-05-02 13:03 UTC, bmchugh-ch approved these changes

2024-05-03 09:32 UTC, merged